# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '802bf5ab-d282-4f89-9788-3f835e427db1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMTemplateDeployment'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/rishabhsajmera/AzureRmPipeline-repo/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName armp'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    
